FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /app/target/devcalc-api-1.0.0.jar app.jar
EXPOSE 7070
CMD ["java", "-jar", "app.jar"]
