apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: tp2
  labels:
    app: multi-container
spec:
  containers:
  - name: nginx
    image: nginx:1.29.3-alpine-slim
    ports:
    - containerPort: 80
  - name: busybox-sidecar
    image: busybox
    env:
    - name: USER
      value: "root"
    - name: PASSWORD
      value: "123456"
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; wget -qO- http://localhost:80; sleep 10; done"]
