apiVersion: v1
kind: Service
metadata:
  name: internal-service
  namespace: tp2
spec:
  type: ClusterIP
  selector:
    app: multi-container
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
