apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: tp2
spec:
  type: NodePort
  selector:
    app: devcalc
  ports:
  - protocol: TCP
    port: 7070       # Porta interna do cluster
    targetPort: 7070 # Porta do container
    nodePort: 30003  # Porta exposta externamenet
